### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by xuliwalker** [sean-zhuh/SeqTR#10]
Great work! Could you pls provide the pre-trained model? Thanks!

**Comment by sean-zhuh** [comment]
Hi, part of the pre-trained models are already provided, for those missing checkpoints, that's because the download app from server gives an md5 hash error, plus I no longer have access to the GPU server. I'' retrain them in the next few months, :). Or you could train them yourself, cause trainining on an 32 GB V100 card only takes half the day, except for pre-training on visual genome.

**Comment by xuliwalker** [comment]
Thanks for your reply! May I know which version of mmcv-full did you use? Since when I pre-train the model, I encountered the following issue, which is believed to be related to the mmcv-full version. Thanks!


Traceback (most recent call last):
  File "/workspace/SeqTR/tools/train.py", line 11, in <module>
    from seqtr.core import build_optimizer, build_scheduler
  File "/workspace/SeqTR/seqtr/core/__init__.py", line 3, in <module>
    from .layers import *
  File "/workspace/SeqTR/seqtr/core/layers/__init__.py", line 1, in <module>
    from .transformer import AutoRegressiveTransformer, LearnedPositionalEncoding1D, LinearModule
  File "/workspace/SeqTR/seqtr/core/layers/transformer.py", line 15, in <module>
    from mmdet.models.utils import build_linear_layer
  File "/usr/local/lib/python3.9/dist-packages/mmdet/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/usr/local/lib/python3.9/dist-packages/mmdet/models/backbones/__init__.py", line 2, in <module>
    from .csp_darknet import CSPDarknet
  File "/usr/local/lib/python3.9/dist-packages/mmdet/models/backbones/csp_darknet.py", line 11, in <module>
    from ..utils import CSPLayer
  File "/usr/local/lib/python3.9/dist-packages/mmdet/models/utils/__init__.py", line 13, in <module>
    from .point_sample import (get_uncertain_point_coords_with_randomness,
  File "/usr/local/lib/python3.9/dist-packages/mmdet/models/utils/point_sample.py", line 3, in <module>
    from mmcv.ops import point_sample
  File "/usr/local/lib/python3.9/dist-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/usr/local/lib/python3.9/dist-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/usr/local/lib/python3.9/dist-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
